title: Page

tabs:
  content:
    label: Contenu
    columns:
      main:
        width: 2/3
        fields:
          text:
            type: textarea
            size: huge
      sidebar:
        width: 1/3
        sections:
          pages:
            type: pages
            template: default
          files:
            type: files
  seo:
    label: SEO
    fields:
      seoTitle:
        label: Titre SEO
        type: text
      seoDescription:
        label: Description SEO
        type: textarea
        buttons: false
        maxlength: 160
